config/routes.rb
Rails.application.routes.draw do

  get 'events/index'

  get 'events/new'

  get 'events/show'

  root 'sessions#new'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :users, only: [:new, :create, :show]
  resources :events, only: [:index, :new, :create, :show]
  resources :event_attendees
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :creator, class_name: "User"
  has_many :event_attendees, foreign_key: "attendee_event_id"
  has_many :attendees, through: "event_attendees", source: "event_attendee"
  #scope :upcoming, -> { where("date >= ?", Date.current).order(date: :asc) }
  #scope :past, -> { where("date < ?", Date.current).order(date: :desc) }


  def self.upcoming
    where('date >= ?', DateTime.now)
  end

  def self.past
    where('date < ?', DateTime.now)
  end



#  def self.published             ###Example from tutorial online
#    where(status: 'published')
#  end

end

app/models/event_attendee.rb
class EventAttendee < ApplicationRecord
  belongs_to :event_attendee, class_name: 'User'
  belongs_to :attendee_event, class_name: 'Event'
end

app/models/user.rb
class User < ApplicationRecord
  has_many :created_events, foreign_key: "creator_id", class_name: "Event"
  has_many :event_attendees, foreign_key: "event_attendee_id"
  has_many :events, through: "event_attendees", source: "attendee_event"


  def upcoming_events
    self.events.where('date >= ?', DateTime.now)
  end

  def previous_events
    self.events.where('date < ?', DateTime.now)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  include SessionsHelper
end

app/controllers/event_attendees_controller.rb
class EventAttendeesController < ApplicationController
  def create
    @event = Event.find(params[:event_attendee][:attendee_event_id])
    current_user.event_attendees.create!(attendee_event_id: @event.id)
    redirect_to @event
  end

  def destroy
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @prev_events = Event.past
    @upcoming_events = Event.upcoming
  end

  def new
    @event = Event.new
  end

  def create
    @event = current_user.created_events.build(event_params)
    if @event.save
      redirect_to @event
    else
      render 'new'
    end
  end

  def show
    @event = Event.find(params[:id])
    @event_attendees = @event.attendees
  end

    private
    def event_params
      params.require(:event).permit(:name, :date, :location, :description)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user
      session[:current_user_id] = user.id
      redirect_to user_path(user)
    else
      flash.now[:danger] = 'Invalid email'
      render 'new'
    end
  end

  def destroy
    session.delete(:current_user_id)
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to @user
    else
    end
  end

  def show
    @user = User.find(params[:id])
    @upcoming_events = @user.upcoming_events
    @prev_events = @user.previous_events
  end

    private

    def user_params
      params.require(:user).permit(:name, :email)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/event_attendees_helper.rb
module EventAttendeesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def current_user
    @current_user = User.find(session[:current_user_id])
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/index.html.erb
<h3>Upcoming Events</h3>
<% @upcoming_events.each do |event| %>
    <h5><%= link_to event.name, event %></h5>
<% end %>

<h3>Previous Events</h3>
<% @prev_events.each do |event| %>
    <h5><%= link_to event.name, event %></h5>
<% end %>

app/views/events/new.html.erb
<%= form_for @event do |f| %>
    <h2>Create Event</h2>

    <%= f.label :name, "Event Name:" %>
    <%= f.text_field :name, placeholder: "Joey Urbik's birthday" %>

    <%= f.label :date, "Date:" %>
    <%= f.datetime_select :date, ampm: true, default: DateTime.tomorrow + 12.hours %>

    <%= f.label :location, "Location:" %>
    <%= f.text_field :location, placeholder: "Stephen Gerkes' parents' house" %>

    <%= f.label :description, "Event Description:" %>
    <%= f.text_area :description, placeholder: "Optional - add details like what to bring or wear" %>


    <div class="submit">
      <%= f.submit "Create Event" %>
    </div>

<% end %>

app/views/events/show.html.erb
<h1> Event! </h1>


<h3>Event: <%= @event.name %></h3>
<h3>Host: <%= @event.creator.name %></h3>
<h3>Date: <%= @event.date %></h3>
<h3>Location: <%= @event.location %></h3>
<h3>Info: <%= @event.description %></h3>

<h4>Attending</h4>
<% @event_attendees.each do |attendee| %>
    <p><%= attendee.name %></p>
<% end %>



<%= form_for(current_user.event_attendees.build(attendee_event_id: @event.id), :html => {class: "just_button"}) do |f| %>
    <%= f.hidden_field :attendee_event_id %>
    <div class="submit">
      <%= f.submit "Attend!" %>
    </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if session[:current_user_id] %>
        <% @current_user = User.find(session[:current_user_id]) %>
    <% end %>

    <nav>
      <ul>
        <% if @current_user %>
            <li><%= link_to "Your events", user_path(current_user)  %></li>
            <li><%= link_to "Make an event", new_event_path %></li>
            <li><%= link_to "All events", events_path %></li>
            <li><%= link_to "Log out", logout_path, method: "delete" %></li>
        <% else %>
            <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
    <% if @current_user %>
      <p> Logged in as <%= @current_user.name %></p>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<h1>Sign up here!</h1>
<%= form_for @user do |f| %>
    <div>
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>
    <div>
      <%= f.label :email %>
      <%= f.text_field :email %>
    </div>
    <%= submit_tag "Sign up!" %>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.name %></h1>

<h3>Events created</h3>
<% @user.created_events.each do |event| %>
    <h5><%= link_to event.name, event %></h5>
<% end %>

<h3>Future appearances</h3>
<% @upcoming_events.each do |event| %>
    <h5><%= link_to event.name, event %></h5>
<% end %>

<h3>Past appearances</h3>
<% @prev_events.each do |event| %>
    <h5><%= link_to event.name, event %></h5>
<% end %>